/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RekycApp {
    }
    interface RekycBank {
    }
    interface RekycCustomer {
        /**
          * @default 'KYC-4528'
         */
        "customerId": string;
    }
}
declare global {
    interface HTMLRekycAppElement extends Components.RekycApp, HTMLStencilElement {
    }
    var HTMLRekycAppElement: {
        prototype: HTMLRekycAppElement;
        new (): HTMLRekycAppElement;
    };
    interface HTMLRekycBankElement extends Components.RekycBank, HTMLStencilElement {
    }
    var HTMLRekycBankElement: {
        prototype: HTMLRekycBankElement;
        new (): HTMLRekycBankElement;
    };
    interface HTMLRekycCustomerElement extends Components.RekycCustomer, HTMLStencilElement {
    }
    var HTMLRekycCustomerElement: {
        prototype: HTMLRekycCustomerElement;
        new (): HTMLRekycCustomerElement;
    };
    interface HTMLElementTagNameMap {
        "rekyc-app": HTMLRekycAppElement;
        "rekyc-bank": HTMLRekycBankElement;
        "rekyc-customer": HTMLRekycCustomerElement;
    }
}
declare namespace LocalJSX {
    interface RekycApp {
    }
    interface RekycBank {
    }
    interface RekycCustomer {
        /**
          * @default 'KYC-4528'
         */
        "customerId"?: string;
    }

    interface RekycCustomerAttributes {
        "customerId": string;
    }

    interface IntrinsicElements {
        "rekyc-app": RekycApp;
        "rekyc-bank": RekycBank;
        "rekyc-customer": Omit<RekycCustomer, keyof RekycCustomerAttributes> & { [K in keyof RekycCustomer & keyof RekycCustomerAttributes]?: RekycCustomer[K] } & { [K in keyof RekycCustomer & keyof RekycCustomerAttributes as `attr:${K}`]?: RekycCustomerAttributes[K] } & { [K in keyof RekycCustomer & keyof RekycCustomerAttributes as `prop:${K}`]?: RekycCustomer[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rekyc-app": LocalJSX.IntrinsicElements["rekyc-app"] & JSXBase.HTMLAttributes<HTMLRekycAppElement>;
            "rekyc-bank": LocalJSX.IntrinsicElements["rekyc-bank"] & JSXBase.HTMLAttributes<HTMLRekycBankElement>;
            "rekyc-customer": LocalJSX.IntrinsicElements["rekyc-customer"] & JSXBase.HTMLAttributes<HTMLRekycCustomerElement>;
        }
    }
}
